apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-vault-signer
  namespace: kube-system
---
kind: CluterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kube-vault-signer
subjects:
- kind: ServiceAccount
  name: kube-vault-signer
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:controller:certificate-controller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-vault-signer
  namespace: kube-system
  labels:
    k8s-app: kube-vault-signer
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kube-vault-signer
  template:
    metadata:
      labels:
        k8s-app: kube-vault-signer
    spec:
      serviceAccountName: kube-vault-signer
      containers:
      - name: kube-vault-signer
        image: thatsmrtalbot/kube-vault-signer:__VERSION__
        args:
          - controller
          - -vault-address=https://vault.example.com
          - -vault-auth=kubernetes
          - -kubernetes-auth-role=kube-vault-signer
