[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.3"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.10.3"

[[constraint]]
  name = "github.com/hashicorp/vault"
  version = "v0.10.4"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.3"

[[override]]
  name = "github.com/docker/distribution"
  branch = "master"