[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.3"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.3"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.10.3"

[[override]]
  name = "github.com/hashicorp/vault"
  branch = "master"
  # version = "v0.10.2"

[[override]]
  name = "github.com/docker/distribution"
  branch = "master"